version: "3"
services: 
    future-table: 
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - '/app/node_modules'
        ports: 
            - "3000:3000"
        container_name: future-table
        stdin_open: true

